### ISSUE TITLE
integration test: connection timed out; no servers could be reached

### ISSUE THREAD

**Issue by tstromberg** [kubernetes/minikube#3163]
Example: https://storage.googleapis.com/minikube-builds/logs/3161/Linux-VirtualBox.txt

   --- FAIL: TestFunctional/DNS (101.69s)
    	util.go:185: Error ;; connection timed out; no servers could be reached
    		
    		command terminated with exit code 1
    		 running command [exec busybox-qf5m4 nslookup kubernetes]. Return code: exit status 1
    	util.go:185: Error ;; connection timed out; no servers could be reached
    		
    		command terminated with exit code 1
    		 running command [exec busybox-qf5m4 nslookup kubernetes]. Return code: exit status 1
    	util.go:185: Error ;; connection timed out; no servers could be reached
    		
    		command terminated with exit code 1
    		 running command [exec busybox-qf5m4 nslookup kubernetes]. Return code: exit status 1
    	cluster_dns_test.go:62: running nslookup in pod:Temporary Error: Error running command. Error  exit status 1. Output: ;; connection timed out; no servers could be reached
    		
    		command terminated with exit code 1
    		
    		Temporary Error: Error running command. Error  exit status 1. Output: ;; connection timed out; no servers could be reached
    		
    		command terminated with exit code 1
    		
    		Temporary Error: Error running command. Error  exit status 1. Output: ;; connection timed out; no servers could be reached

**Comment by tstromberg** [comment]
git bisect points to this change, after which the test no longer waits for the pods to be running:

https://github.com/kubernetes/minikube/commit/0a5efe156c9c303bb9ee1746d3015af06b78059a

I'll see what I can do to extend the timeout, or better yet, improve the error message.
