### PR TITLE
Upgrade Docker, from 18.09.6 to 18.09.7

### PR DESCRIPTION
**Pull request by afbjorklund**
runc v1.0.0-rc8-0-g425e105

    containerd v1.2.6

### CODE REVIEW

**Comment by afbjorklund** [comment]
Currently this doesn't build properly with go1.10, so might need to upgrade Buildroot to get go1.12 ?

```
# runtime/internal/sys
../../../../../../../host/lib/go/src/runtime/internal/sys/stubs.go:11:7: const initializer 1 * (1 - GoarchArm64) + 16 * GoarchArm64 is not a constant
../../../../../../../host/lib/go/src/runtime/internal/sys/stubs.go:11:22: undefined: GoarchArm64
Makefile:173: receptet för målet ”bin/containerd-shim” misslyckades

```

**Comment by afbjorklund** [comment]
Hmm, must be something else - because containerd v1.2.5 is also failing, with the same build error...

**Comment by afbjorklund** [comment]
Rebuilding both the host go packages fixed it, so just something about the local out/buildroot...

**Comment by afbjorklund** [comment]
The Jenkins build failed due to #4345
