### PR TITLE
Upgrade crio to 1.15.0

### PR DESCRIPTION
**Pull request by afbjorklund**
The repository was moved to a separate organization
    
strings.ReplaceAll only work in go1.12, not go1.10
    
Need to create conmon/config.h without tags and git
    
The configuration _needs_ to be updated (yet again)

### CODE REVIEW

**Comment by afbjorklund** [comment]
Currently doesn't build anymore, due to https://github.com/cri-o/cri-o/issues/2450

`runtime_vm.go:175:20: undefined: strings.ReplaceAll`

**Comment by afbjorklund** [comment]
Reported the workarounds for conmon/config.h as https://github.com/cri-o/cri-o/issues/2575

**Comment by medyagh** [comment]
I could upgrade the go version on the jenkins nodes, would that be sufficient ? or do we need to update the travis config too?

**Comment by afbjorklund** [comment]
@medyagh : it is the buildroot go, and it will be upgraded when we move from 2018.x to 2019.x
But it was working ok in the previous cri-o (1.14) and it seemed like a petty reason to require it ?

File: deploy/iso/minikube-iso/package/crio-bin/crio.conf.default [hunk 1]
```diff
@@ -202,15 +217,19 @@ gid_mappings = ""
...
+# and manage its lifecycle.
+manage_network_ns_lifecycle = false
+
+# The "crio.runtime.runtimes" table defines a list of OCI compatible runtimes.
+# The runtime to use is picked based on the runtime_handler provided by the CRI.
+# If no runtime_handler is provided, the runtime will be picked based on the level
+# of trust of the workload.
+
+[crio.runtime.runtimes.runc]
+runtime_path = ""
```
Comment (saschagrunert) [inline deploy/iso/minikube-iso/package/crio-bin/crio.conf.default]: Please be aware that `runc` has to be in `$PATH` to let this work during runtime.

File: deploy/iso/minikube-iso/package/crio-bin/crio-bin.patch [hunk 2]
```diff
@@ -0,0 +1,39 @@
+diff --git a/Makefile b/Makefile
+index de79f63..a9ea13b 100644
+--- a/Makefile
++++ b/Makefile
+@@ -136,7 +136,7 @@ crio.conf: bin/crio
+ release-note: ${RELEASE_TOOL}
+ 	${RELEASE_TOOL} -n $(release)
+ 
+-conmon/config.h: git-vars cmd/crio-config/config.go oci/oci.go
++conmon/config.h: cmd/crio-config/config.go oci/oci.go
```
Comment (saschagrunert) [inline deploy/iso/minikube-iso/package/crio-bin/crio-bin.patch]: So the git executable is not available within your build environment? Because the git-vars target was introduced to actually fix this, but it only checks for the `.git` folder. I think I can improve this :)

Comment (afbjorklund) [reply deploy/iso/minikube-iso/package/crio-bin/crio-bin.patch]: Actually it was worse... We do have git, but that's for our buildroot. Thus it recorded [commits from a different project](https://github.com/kubernetes/minikube/issues/3454). We build all our packages from tarballs, so have to supply the matching commit for each one.

The main problem here is that the "git-vars" target forces the conmon/config.h to be re-generated, even if it already exists (same with crio.conf too)

File: deploy/iso/minikube-iso/package/crio-bin/crio.conf.default (hunk 1 above)
Comment (afbjorklund) [reply deploy/iso/minikube-iso/package/crio-bin/crio.conf.default]: Yeah, this is what the crio generated by default. Compare it with our config (above).

    runtime_path = "/usr/bin/runc"

I generated and added the default config, since it changes and breaks _all. the. time_

* plugin_dir, plugin_dirs

File: deploy/iso/minikube-iso/package/crio-bin/crio-bin.patch (hunk 2 above)
Comment (saschagrunert) [reply deploy/iso/minikube-iso/package/crio-bin/crio-bin.patch]: Ah I see, thanks. Let's see if we can get rid of the git-vars dependency of this target entirely.

**Comment by afbjorklund** [comment]
On the plus side, the new release seem to be working fine with the tweaks made.

Haven't tried it with the new runc yet, need to make a trial run with all the changes.

File: deploy/iso/minikube-iso/package/crio-bin/crio.conf.default (hunk 1 above)
Comment (saschagrunert) [reply deploy/iso/minikube-iso/package/crio-bin/crio.conf.default]: I guess it should work fine :)

**Comment by tstromberg** [comment]
@minikube-bot OK to test
